// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0y29Vlz8ABQDTZG6k0amd2z6q4a1js3I',
    appId: '1:575239767004:web:3a6512f6a4d4c143710519',
    messagingSenderId: '575239767004',
    projectId: 'myfirebasefluttertest-80764',
    authDomain: 'myfirebasefluttertest-80764.firebaseapp.com',
    storageBucket: 'myfirebasefluttertest-80764.appspot.com',
    measurementId: 'G-BM7FB4ZMY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsKSzI5IpioFPYhE0ngiILOD13c0WgKXc',
    appId: '1:575239767004:android:da68b14016e45142710519',
    messagingSenderId: '575239767004',
    projectId: 'myfirebasefluttertest-80764',
    storageBucket: 'myfirebasefluttertest-80764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5afOdKigxrf-dk5Uqnb3bZytx09VFcl8',
    appId: '1:575239767004:ios:fb678d464ab28a1e710519',
    messagingSenderId: '575239767004',
    projectId: 'myfirebasefluttertest-80764',
    storageBucket: 'myfirebasefluttertest-80764.appspot.com',
    iosClientId: '575239767004-2aqked7fubs69fk5ntm4sk1f9fsurkg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5afOdKigxrf-dk5Uqnb3bZytx09VFcl8',
    appId: '1:575239767004:ios:fb678d464ab28a1e710519',
    messagingSenderId: '575239767004',
    projectId: 'myfirebasefluttertest-80764',
    storageBucket: 'myfirebasefluttertest-80764.appspot.com',
    iosClientId: '575239767004-2aqked7fubs69fk5ntm4sk1f9fsurkg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebase',
  );
}
